[project]
name = "memori"
description = "A python library for creating memoized data and code for neuroimaging pipelines"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT License" }
authors = [{ name = "Andrew Van", email = "vanandrew@wustl.edu" }]
keywords = ["neuroimaging", "pipeline", "memoization"]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]
urls = { github = "https://github.com/vanandrew/memori" }
version = "0.3.6"
dynamic = ["entry-points"]

[project.optional-dependencies]
dev = [
  "black >= 22.3.0",
  "coverage[toml] >= 5.5",
  "pytest >= 6.2.5",
  "pytest-pycodestyle >= 2.2.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip-safe = true

[tool.setuptools.packages.find]
exclude = ["tests"]

[tool.black]
line-length = 120
target-version = ["py37", "py38", "py39", "py310"]

[tool.pytest.ini_options]
addopts = "-v --pycodestyle --junitxml=test-results/junit.xml"
testpaths = [
    "tests",
    "memori"
]

[tool.coverage.run]
command_line = "-m pytest"
source = ["memori"]

[tool.coverage.report]
show_missing = true
precision = 2
